ci: ctsm nginx fix Mixed Content http https

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -58,6 +58,7 @@ jobs:
           wait $FRONTEND_PID
           FRONTEND_STATUS=$?
           
-          echo "$BACKEND_STATUS: " $BACKEND_STATUS
-          echo "$FRONTEND_STATUS: " $FRONTEND_STATUS
-
+          if [ $BACKEND_STATUS -ne 0 ] || [ $FRONTEND_STATUS -ne 0 ]; then
+            echo "Deployment failed!"
+            exit 1
+          fi
